### ISSUE TITLE
ДЗ 8

### ISSUE THREAD

**Issue by AndyAnderyan** [YulianaRop/Basik#11]
### **Завдання 8**
Вам може допомогти в вирішені цього завдання, ось таке правило:
```css
  h1 span {
      width: min-content;
      display: inline-block;
  }
```

### **Завдання 1-7 - зроблені на 100%**
